# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week5_alamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'

  # Pods for week5_alamofire

  target 'week5_alamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'week5_alamofireUITests' do
    # Pods for testing
  end

end
