# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week5_kakao' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week5_kakao

  target 'week5_kakaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'week5_kakaoUITests' do
    # Pods for testing
  end

end
